name: Feature Request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
      description: Describe the use case.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: false
